services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myplanner
      POSTGRES_PASSWORD: ${PASS_DB}
      POSTGRES_DB: myplanner
    network_mode: host
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myplanner -d myplanner"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
